### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by marwa811** [liweizhuo001/FCA-Map#1]
I need to test FCA-Map tool for an ontology matching task, but this link https://pan.baidu.com/s/1i4SKy4t is broken .. could you send me a working link to download the configuration file.

**Comment by liweizhuo001** [comment]
you can use this linkage to download the file https://drive.google.com/file/d/10Qd0rKQkkX7M7zhPhFB7Ew9VmI47ZQ5x/view?usp=sharing

**Comment by marwa811** [comment]
Thanks
